bump most deps
now encountering an overflow error in the quickcheck properties:

```
<...>
thread 'test::parse_pretty::roundtrip::parse_pretty_roundtrip' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', rep_lang_concrete_syntax/src/parse.rs:26:45
thread 'test::parse_pretty::roundtrip::parse_pretty_roundtrip' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: (WrappedExpr(Lit(LInt(-9223372036854775808))))
Error: "called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }"', /home/mhueschen/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-1.0.3/src/tester.rs:165:28
```

it seems like `-(2 ^ 63)` is unable to be parsed into an i64 via
`string.parse::<i64>()`. which seems weird, because it should fit...